### PR TITLE
major: upgrade deps, node 20, actions

### PR DESCRIPTION
**Pull request by smlgbl**

### CODE REVIEW

**Comment by de-vri-es** [comment]
Looks good. Thanks!

I think we can release this with only a minor version bump though. The public behaviour of the action didn't change. Or did I miss something?

**Comment by smlgbl** [comment]
No, you are right. No behaviour changes.

**Comment by de-vri-es** [comment]
Okay. Released as `v2.1.0`.

Thanks for the PR! :partying_face:

**Comment by smlgbl** [comment]
Thanks for merging, but you did not create a release. Any reason?

**Comment by de-vri-es** [comment]
I tagged `v2.1.0`, `v2.1` and `v2`. Note that I had to downgrade to `node16`. See #28.

**Comment by de-vri-es** [comment]
Ah, I forgot about the github release thingy. Made the new releases now too.

**Comment by de-vri-es** [comment]
From the docs, I agree that node20 should be fine. Lets see what we find out at #28. In the mean time the downgrade is the safe option.

But if it's an outdated custom runner, then I think we can just add a note to the README to use `v2.0` for those cases, and upgrade to node20 again.

**Comment by de-vri-es** [comment]
Alright, upgraded and released again :p

Thanks again for doing the maintenance!

**Comment by michaelmcguire** [comment]
Was there a reason that the `node_modules` got included in the repo with this update?

**Comment by de-vri-es** [comment]
Yes, the javascript code is required for workflows using the action. They don't run the typescript compiler first.

(It was already included before too.)

**Pull request merged**
